// Capturas de pantalla para el manual. Uso: node tools/manual_shots.js <carpeta_build> <lang>
const { chromium } = require('playwright');
const path = require('path');
(async () => {
  const [dir, lang] = [process.argv[2], process.argv[3] || 'es'];
  const out = path.join(dir, 'shots', lang); require('fs').mkdirSync(out, { recursive: true });
  const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
  const p = await b.newPage({ viewport: { width: 390, height: 780 }, deviceScaleFactor: 2, locale: lang });
  const errs = []; p.on('pageerror', e => errs.push(e.message));
  const url = 'file://' + path.join(dir, 'index.html');
  await p.goto(url); await p.evaluate(l => { localStorage.setItem('valve-app-theme2', 'dark'); localStorage.setItem('valve-app-language', l); }, lang);
  const go = async (h, wait = 700) => { await p.evaluate(() => document.querySelectorAll('dialog[open]').forEach(d => d.close())).catch(() => { }); await p.goto(url + h); await p.waitForTimeout(wait); await p.evaluate(() => document.querySelectorAll('dialog[open]').forEach(d => d.close())); };
  const shot = async name => { await p.screenshot({ path: path.join(out, name + '.png') }); };
  const el = async (sel, name) => { const e = await p.$(sel); if (e) { await e.scrollIntoViewIfNeeded(); await p.waitForTimeout(250); await e.screenshot({ path: path.join(out, name + '.png') }); } };
  const scrollTo = async sel => { await p.evaluate(s => { const e = document.querySelector(s); if (e) { const y = e.getBoundingClientRect().top + scrollY - 70; scrollTo(0, y); } }, sel); await p.waitForTimeout(300); };
  await go('#/'); await shot('home');
  await p.click('[data-hc="how"]'); await p.waitForTimeout(200); await shot('home_how');
  await go('#/v/sjm/aortic/0/23', 900); await shot('detail');
  await scrollTo('#size-card'); await shot('sizecard');
  await scrollTo('.dim-box'); await shot('dims');
  await scrollTo('#sec-specs'); await shot('specs');
  await scrollTo('#sec-fluoro'); await shot('fluoro_sec');
  await go('#/fluoro', 900); await shot('atlas');
  await go('#/id'); await p.click('[data-q="ring"][data-a="n"]'); await p.waitForTimeout(200); await shot('ident');
  await scrollTo('#id-res'); await shot('ident_res');
  await go('#/'); await p.evaluate(() => openDialog('dlg-calc')); await p.waitForTimeout(300);
  await p.selectOption('#c-brand', 'sjm'); await p.waitForTimeout(100); await p.selectOption('#c-sub', '0'); await p.waitForTimeout(100);
  const opts = await p.$$eval('#c-size option', o => o.map(x => x.value).filter(Boolean)); if (opts.length) await p.selectOption('#c-size', opts[Math.min(3, opts.length - 1)]);
  await p.waitForTimeout(300); await shot('calc');
  await go('#/sim/sjm/aortic/0/23?v=side', 3000); await shot('sim_top');
  await scrollTo('#sim-stage'); await shot('sim_side');
  await scrollTo('.sim-layers'); await shot('sim_layers');
  await go('#/sim/sjm/aortic/0/23?v=3d', 2800); await scrollTo('#sim-stage'); await shot('sim_3d');
  await go('#/sim/sjm/aortic/0/23?v=xray', 2800); await p.evaluate(() => { state.sim.xtilt = 0.35; }); await p.click('[data-sv="xray"]'); await p.waitForTimeout(300); await scrollTo('#sim-stage'); await shot('sim_xray');
  await go('#/sim/sjm/aortic/0/23?v=side&lca=12&rca=15&sov=30&stj=27&stjh=20', 2800); await p.evaluate(() => document.querySelector('.sim-ct').open = true);
  await scrollTo('.sim-ct'); await shot('sim_ct_in'); await scrollTo('#sim-stage'); await shot('sim_ct');
  await scrollTo('#sim-metrics'); await shot('sim_metrics');
  await scrollTo('#sim-cmp'); await shot('sim_cmp');
  await go('#/sim/sjm/aortic/0/23?v=top', 2800); await scrollTo('#sim-stage'); await shot('sim_topview');
  await go('#/cmp/sjm/aortic/0/23/carbomedics/aortic/0/23', 900); await shot('cmp'); await scrollTo('.cmp-tbl'); await shot('cmp_tbl');
  await go('#/guia', 900); await shot('guide');
  await go('#/'); await p.evaluate(() => openDialog('dlg-menu')); await p.waitForTimeout(400); await shot('menu');
  await p.evaluate(() => { document.querySelector('#dlg-menu').close(); openDialog('dlg-share'); }); await p.waitForTimeout(400); await shot('qr');
  await p.evaluate(() => { document.querySelector('#dlg-share').close(); openDialog('dlg-credits'); }); await p.waitForTimeout(400); await shot('credits');
  await p.evaluate(() => { document.querySelector('#dlg-credits').close(); }); await go('#/v/sjm/aortic/0/23', 600); await p.evaluate(() => openMaker('sjm')); await p.waitForTimeout(300); await shot('maker');
  await go('#/'); await p.evaluate(() => demoStart(false)); await p.waitForTimeout(1500); await shot('demo'); await p.evaluate(() => demoStop());
  await p.setViewportSize({ width: 1100, height: 760 }); await go('#/sim/sjm/aortic/0/23?v=side', 3000); await shot('desktop_sim');
  console.log(lang, 'errors', errs);
  await b.close();
})();
